version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: calcom_postgres
    restart: unless-stopped
    ports: ["5450:5432"]
    environment:
      POSTGRES_DB: calcom
      POSTGRES_USER: calcom
      POSTGRES_PASSWORD: calcom
    volumes:
      - calcom_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calcom"]
      interval: 10s
      timeout: 5s
      retries: 8

  mailhog:
    image: mailhog/mailhog:latest
    container_name: calcom_mailhog
    restart: unless-stopped
    ports: ["8025:8025", "1025:1025"]

  api:
    build:
      context: ../..
      dockerfile: infra/docker/api/Dockerfile
    container_name: calcom_api
    env_file:
      - ./.env.docker
    environment:
      HOST: "0.0.0.0"
      PORT: "80"
      # make sure API hits the right DB (don't rely on .env.docker defaults)
      DATABASE_URL: "postgresql://calcom:calcom@postgres:5432/calcom?schema=public"
      EMAIL_SERVER_HOST: "mailhog"
      EMAIL_SERVER_PORT: "1025"
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["3002:80"]

  web:
    build:
      context: ../..
      dockerfile: infra/docker/web/Dockerfile.simple
      # >>> THESE ARGS ARE USED DURING yarn build <<<
      args:
        NEXT_PUBLIC_WEBAPP_URL: "https://evalify-cal.y34zyo.easypanel.host"
        NEXT_PUBLIC_WEBSITE_URL: ""
        NEXT_PUBLIC_EMBED_LIB_URL: "https://evalify-cal.y34zyo.easypanel.host/embed/embed.js"
        NEXTAUTH_URL: "https://evalify-cal.y34zyo.easypanel.host"
    container_name: calcom_web
    env_file:
      - ./.env.docker
    environment:
      HOST: "0.0.0.0"
      PORT: "3001"
      # keep DB/email explicit at runtime too
      DATABASE_URL: "postgresql://calcom:calcom@postgres:5432/calcom?schema=public"
      EMAIL_SERVER_HOST: "mailhog"
      EMAIL_SERVER_PORT: "1025"
      E2E_TEST_MAILHOG_ENABLED: "1"
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["3001:3001"]
    # ensure Next listens on all interfaces
    command: ["sh","-lc","yarn workspace @calcom/web start -p 3001 -H 0.0.0.0"]

volumes:
  calcom_db_data:
